### ISSUE TITLE
Looking for precompiled binary.

### ISSUE THREAD

**Issue by fivetwelve** [sbarex/SourceCodeSyntaxHighlight#27] opened 2020-02-02 03:48 UTC
The readme makes mention of pre-compiled binaries but I cannot locate it here in the repo nor if there is a website associated for its download.

Could you provide some more information about it or its location? Thank you!

**Comment by sbarex** [comment] 2020-02-02 08:07
duplicate of #26

**Closed by sbarex** 2020-02-02 08:07 UTC

**Comment by fivetwelve** [comment] 2020-02-02 23:18
Cheers for that. I appreciate the work you put into this. 🙏

Might I suggest adding a note about the location (Releases > Assets or Tags > Downloads)  in your Readme?
